<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllPosts()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT n FROM AppBundle:News n WHERE n.postType = :postType ORDER BY n.createdAt DESC'
            )
            ->setParameter('postType', "post")
            ->getResult();
    }

    public function findAllPages()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT n FROM AppBundle:News n WHERE n.postType = :postType ORDER BY n.parent ASC, n.title ASC'
            )
            ->setParameter('postType', "page")
            ->getResult();
    }

    public function findPagesAsTree()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT n FROM AppBundle:News n WHERE n.postType = :postType AND n.parent IS NULL ORDER BY n.title ASC'
            )
            ->setParameter('postType', "page")
            ->getResult();
    }

    public function searchPages($query)
    {
        return $this->createQueryBuilder('n')
            ->where('n.postType = :postType')
            ->andWhere(
                'n.title LIKE :query
                OR n.url LIKE :query
                OR n.description LIKE :query
                OR n.contents LIKE :query
                OR n.pageTitle LIKE :query
                OR n.pageDescription LIKE :query
                OR n.pageKeyword LIKE :query'
            )
            ->setParameter('postType', 'page')
            ->setParameter('query', '%'.$query.'%')
            ->orderBy('n.title', 'ASC')
            ->getQuery()
            ->getResult();
    }

    public function searchPosts($query, $categoryId = null)
    {
        $qb = $this->createQueryBuilder('n')
            ->where('n.postType = :postType')
            ->andWhere(
                'n.title LIKE :query
                OR n.url LIKE :query
                OR n.description LIKE :query
                OR n.contents LIKE :query
                OR n.pageTitle LIKE :query
                OR n.pageDescription LIKE :query
                OR n.pageKeyword LIKE :query'
            )
            ->setParameter('postType', 'post')
            ->setParameter('query', '%'.$query.'%')
            ->orderBy('n.createdAt', 'DESC');

        if (null !== $categoryId) {
            $qb
                ->leftJoin('n.category', 'c')
                ->andWhere('c.id = :categoryId')
                ->setParameter('categoryId', $categoryId);
        }

        return $qb->getQuery()->getResult();
    }
}
