<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllPosts()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT n FROM AppBundle:News n WHERE n.postType = :postType ORDER BY n.createdAt DESC'
            )
            ->setParameter('postType', "post")
            ->getResult();
    }

    public function findAllPages()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT n FROM AppBundle:News n WHERE n.postType = :postType ORDER BY n.parent ASC, n.title ASC'
            )
            ->setParameter('postType', "page")
            ->getResult();
    }

    public function findPagesAsTree()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT n FROM AppBundle:News n WHERE n.postType = :postType AND n.parent IS NULL ORDER BY n.title ASC'
            )
            ->setParameter('postType', "page")
            ->getResult();
    }
}
