<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllPosts()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT n FROM AppBundle:News n WHERE n.postType = :postType ORDER BY n.createdAt DESC'
            )
            ->setParameter('postType', "post")
            ->getResult();
    }

    public function findAllPages()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT n FROM AppBundle:News n WHERE n.postType = :postType ORDER BY n.createdAt DESC'
            )
            ->setParameter('postType', "page")
            ->getResult();
    }

    public function countPostsByDay(\DateTime $from, \DateTime $to)
    {
        return $this->createQueryBuilder('n')
            ->select("SUBSTRING(n.createdAt, 1, 10) AS day, COUNT(n.id) AS total")
            ->where('n.createdAt BETWEEN :from AND :to')
            ->setParameter('from', $from)
            ->setParameter('to', $to)
            ->groupBy('day')
            ->orderBy('day', 'ASC')
            ->getQuery()
            ->getArrayResult();
    }

    public function topViewed($limit = 10)
    {
        return $this->createQueryBuilder('n')
            ->select('n.id, n.title, n.viewCounts, n.url')
            ->orderBy('n.viewCounts', 'DESC')
            ->setMaxResults((int)$limit)
            ->getQuery()
            ->getArrayResult();
    }
}
